
[package]
name = "tui-plotter"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = "0.20"  # Change to the latest version
crossterm = "0.25"
plotters = "0.3"
braille-rs = "1.0.0"
cc = "1.0"

[build-dependencies]
cc = "1.0"
