
[package]
name = "tui-plotter"
version = "0.1.0"
edition = "2021"

[dependencies]
tui = "0.19"
crossterm = "0.25"
plotters = "0.3"
braille-rs = "1.0.0"         # Corrected version
cc = "1.0"

[build-dependencies]
cc = "1.0"
